title: Cozy Computer
author: Patrick McCarver
email: patrick@cozy.computer
average_reading_speed_words_per_minute: 250
description: >-
  Be cozy and learn things with me (Patrick McCarver)
baseurl: ""
url: "https://cozy.computer"
twitter_username: cozy_computer
github_username: Merklebros
permalink: /:title
collections:
  - journal_entries
plugins:
  - jekyll-feed
